#!/usr/bin/env bash
set -euo pipefail

# Pass a source-specific GitHub URL via REPO_URL or as the first argument.
# The public launch URL should carry tracked_source only and no section anchor.

FORM_ID="261483634936466"
FORM_URL="https://form.jotform.com/${FORM_ID}"
SUBMIT_URL="https://submit.jotform.com/submit/${FORM_ID}"
REPO_URL="${REPO_URL:-${1:-https://github.com/agent-valve-ai/Agent-Valve-Survey?tracked_source=github_readme}}"

url_param() {
  local key="$1"
  local query="${REPO_URL#*[?]}"
  query="${query%%#*}"
  printf '%s\n' "$query" | tr '&' '\n' | sed -nE "s/^${key}=//p" | head -n 1
}

TRACKED_SOURCE_VALUE="$(url_param tracked_source)"
TRACKED_MEDIUM_VALUE="$(url_param tracked_medium)"
TRACKED_CAMPAIGN_VALUE="$(url_param tracked_campaign)"
TRACKED_LINK_ID_VALUE="$(url_param tracked_link_id)"

: "${TRACKED_SOURCE_VALUE:=github_readme}"
: "${TRACKED_MEDIUM_VALUE:=github}"
: "${TRACKED_CAMPAIGN_VALUE:=agent_valve_survey_v1}"
: "${TRACKED_LINK_ID_VALUE:=github_readme_direct}"

form_html="$(curl -fsSL "$FORM_URL")"

field_name_nth() {
  local contains="$1"
  local nth="$2"
  local raw
  raw="$(
    printf '%s' "$form_html" |
      grep -oE 'name="[^"]+"' |
      sed -nE 's/name="([^"]+)"/\1/p' |
      grep -F "$contains" |
      sed -n "${nth}p"
  )"
  if [[ -z "$raw" ]]; then
    printf 'Could not locate survey field matching: %s\n' "$contains" >&2
    exit 1
  fi
  printf '%s' "$raw" | sed 's/\[\]$//'
}

field_name() {
  field_name_nth "$1" 1
}

SURVEY_VERSION="$(field_name "survey_version")"
SUBMITTED_VIA="$(field_name "submitted_via")"
TRACKED_SOURCE="$(field_name "tracked_source")"
TRACKED_MEDIUM="$(field_name "tracked_medium")"
TRACKED_CAMPAIGN="$(field_name "tracked_campaign")"
TRACKED_CHANNEL="$(field_name "tracked_channel")"
TRACKED_COMMUNITY="$(field_name "tracked_community")"
TRACKED_LINK_ID="$(field_name "tracked_link_id")"
LANDING_PAGE_URL="$(field_name "landing_page_url")"
AGENT_TYPE="$(field_name "agent_type")"
AGENT_PLATFORM="$(field_name "agent_platform")"
ACTS_ON_BEHALF_OF="$(field_name "acts_on_behalf_of")"
RUNTIME_DEVICE_TYPE="$(field_name "runtime_device_type")"
RELIABLE_ACCESS_METHODS="$(field_name "reliable_access_methods")"
BUSINESS_CONTACT_FREQUENCY="$(field_name "business_contact_frequency")"
AUTONOMY_LEVEL="$(field_name "autonomy_level")"
COMMON_USE_CASES="$(field_name "common_use_cases")"
OTHER_COMMON_USE_CASE="$(field_name "other_common_use_case")"
TOP_COMMON_USE_CASE_1="$(field_name "top_common_use_case_1")"
TOP_COMMON_USE_CASE_2="$(field_name "top_common_use_case_2")"
TOP_COMMON_USE_CASE_3="$(field_name "top_common_use_case_3")"
LLM_MODELS_USED="$(field_name "llm_models_used")"
EXACT_LLM_MODEL_NAMES="$(field_name "exact_llm_model_names")"
OWNER_LOCATIONS="$(field_name "owner_locations")"
OWNER_LOCATION_FLAGS="$(field_name "owner_location_flags")"
TARGET_BUSINESS_LOCATIONS="$(field_name "target_business_locations")"
TARGET_LOCATION_FLAGS="$(field_name "target_location_flags")"
INDUSTRIES_CONTACTED="$(field_name "industries_contacted")"
INDUSTRIES_CONTACT_FREQUENCY="$(field_name "industries_contact_frequency")"
TOP_BOTTLENECK_INDUSTRIES="$(field_name "top_bottleneck_industries")"
SERVICES_TRIED="$(field_name "services_tried")"
SERVICES_TRIED_FREQUENCY="$(field_name "services_tried_frequency")"
GOODS_TRIED="$(field_name "goods_tried")"
GOODS_TRIED_FREQUENCY="$(field_name "goods_tried_frequency")"
PURCHASING_DIFFICULTY_FACTORS="$(field_name "purchasing_difficulty_factors")"
TECHNICAL_ISSUES="$(field_name "technical_issues")"
TOP_BOTTLENECK_REASONS="$(field_name "top_bottleneck_reasons")"
BOTTLENECK_FREQUENCY_OVERALL="$(field_name "bottleneck_frequency_overall")"
BOTTLENECK_FREQUENCY_MATRIX="$(field_name "bottleneck_frequency_matrix")"
SIMPLEST_CONNECTION_METHODS="$(field_name "simplest_connection_methods")"
BEST_CONTACT_CHANNELS="$(field_name "best_contact_channels")"
WORST_CONTACT_CHANNELS="$(field_name "worst_contact_channels")"
DISCOVERABILITY_SEARCH_SOURCES="$(field_name "discoverability_search_sources")"
SEARCH_FIRST_SOURCES="$(field_name "search_first_sources")"
SEARCH_FALLBACK_SOURCES="$(field_name "search_fallback_sources")"
PURCHASE_DECISION_INFLUENCED="$(field_name "purchase_decision_influenced_by_contact_ease")"
SELECTED_DIFFERENT_BUSINESS="$(field_name "selected_different_business_due_to_access")"
PROVIDER_CHOICE_FACTORS="$(field_name "provider_choice_factors")"
AGENT_POLICY_CLARITY="$(field_name "agent_policy_clarity")"
USEFUL_PERMISSION_MODEL="$(field_name "useful_permission_model")"
EASIEST_VERIFICATION_METHODS="$(field_name "easiest_verification_methods")"
SECURITY_SAFETY_BLOCKERS="$(field_name "security_safety_blockers")"
CAUTION_RISK_CONCERNS="$(field_name "caution_risk_concerns")"
SENSITIVE_ACTION_APPROVAL_MODEL="$(field_name "sensitive_action_approval_model")"
BUSINESS_SAFETY_MEASURES="$(field_name "business_safety_measures")"
TASK_SUCCESS_PERCENTAGE="$(field_name "task_success_percentage")"
FAILURE_OUTCOMES="$(field_name "failure_outcomes")"
SUCCESS_RATE_IMPROVEMENTS="$(field_name "success_rate_improvements")"
OVERALL_DIFFICULTY_RATING="$(field_name "overall_difficulty_rating")"
OVERALL_BOTTLENECK_FREQUENCY_RATING="$(field_name "overall_bottleneck_frequency_rating")"
BOTTLENECK_SEVERITY_MATRIX="$(field_name "bottleneck_severity_matrix")"
PRIORITY_INDUSTRY_RANK_1="$(field_name "priority_industry_rank_1")"
PRIORITY_INDUSTRY_RANK_2="$(field_name "priority_industry_rank_2")"
PRIORITY_INDUSTRY_RANK_3="$(field_name "priority_industry_rank_3")"
IMPROVEMENT_POINT_ALLOCATION="$(field_name "improvement_point_allocation")"
AGENT_READY_RATING="$(field_name "agent_ready_rating")"
GREATEST_BOTTLENECK_INDUSTRIES="$(field_name "greatest_bottleneck_industries")"
SERIOUS_BOTTLENECK_INDUSTRY_RANK_1="$(field_name_nth "serious_bottleneck_industry_rank" 1)"
SERIOUS_BOTTLENECK_INDUSTRY_RANK_2="$(field_name_nth "serious_bottleneck_industry_rank" 2)"
SERIOUS_BOTTLENECK_INDUSTRY_RANK_3="$(field_name_nth "serious_bottleneck_industry_rank" 3)"
TOP_RANKED_INDUSTRY_REASON="$(field_name "top_ranked_industry_reason")"
SINGLE_BIGGEST_IMPROVEMENT="$(field_name "single_biggest_improvement")"
SELF_REPORTED_SOURCE="$(field_name "self_reported_source")"
OPEN_COMMENT_ADDITIONAL_USE_CASES="$(field_name "open_comment_additional_use_cases")"
OPEN_COMMENT_FRUSTRATING_SITUATION="$(field_name "open_comment_frustrating_situation")"
OPEN_COMMENT_BUSINESS_CHANGES="$(field_name "open_comment_business_changes")"
OPEN_COMMENT_SURVEY_FEEDBACK="$(field_name "open_comment_survey_feedback")"
FOLLOW_UP_CONSENT="$(field_name "follow_up_consent")"
OPTIONAL_FOLLOW_UP_CONTACT="$(field_name "optional_follow_up_contact")"

curl_args=(
  -i
  -L
  -X
  POST
  "$SUBMIT_URL"
  -H
  "Content-Type: application/x-www-form-urlencoded"

  --data-urlencode "formID=${FORM_ID}"
  --data-urlencode "submitSource=public_curl"
  --data-urlencode "submitDate=undefined"
  --data-urlencode "uploadServerUrl=https://upload.jotform.com/upload"
  --data-urlencode "eventObserver=1"
  --data-urlencode "website="
  --data-urlencode "simple_spc=${FORM_ID}-${FORM_ID}"

  --data-urlencode "${SURVEY_VERSION}=v1.0"
  --data-urlencode "${SUBMITTED_VIA}=public_curl"
  --data-urlencode "${TRACKED_SOURCE}=${TRACKED_SOURCE_VALUE}"
  --data-urlencode "${TRACKED_MEDIUM}=${TRACKED_MEDIUM_VALUE}"
  --data-urlencode "${TRACKED_CAMPAIGN}=${TRACKED_CAMPAIGN_VALUE}"
  --data-urlencode "${TRACKED_CHANNEL}=public_repo"
  --data-urlencode "${TRACKED_COMMUNITY}="
  --data-urlencode "${TRACKED_LINK_ID}=${TRACKED_LINK_ID_VALUE}"
  --data-urlencode "${LANDING_PAGE_URL}=${REPO_URL}"

  --data-urlencode "${AGENT_TYPE}[]=OpenClaw agent"
  --data-urlencode "${AGENT_TYPE}[]=Claude Code agent"
  --data-urlencode "${AGENT_PLATFORM}[]=API calls"
  --data-urlencode "${AGENT_PLATFORM}[]=MCP client"
  --data-urlencode "${AGENT_PLATFORM}[]=MCP server"
  --data-urlencode "${ACTS_ON_BEHALF_OF}[]=User"
  --data-urlencode "${RUNTIME_DEVICE_TYPE}[]=Cloud VPS"
  --data-urlencode "${RUNTIME_DEVICE_TYPE}[]=Windows mini PC"
  --data-urlencode "${RELIABLE_ACCESS_METHODS}[]=Visible web browser"
  --data-urlencode "${RELIABLE_ACCESS_METHODS}[]=HTTP POST / cURL"
  --data-urlencode "${RELIABLE_ACCESS_METHODS}[]=MCP client"
  --data-urlencode "${BUSINESS_CONTACT_FREQUENCY}=Weekly"
  --data-urlencode "${AUTONOMY_LEVEL}=Partial autonomy"
  --data-urlencode "${COMMON_USE_CASES}[]=Appointment scheduling"
  --data-urlencode "${COMMON_USE_CASES}[]=Customer support"
  --data-urlencode "${OTHER_COMMON_USE_CASE}="
  --data-urlencode "${TOP_COMMON_USE_CASE_1}=Appointment scheduling"
  --data-urlencode "${TOP_COMMON_USE_CASE_2}=Customer support"
  --data-urlencode "${TOP_COMMON_USE_CASE_3}=Purchasing or ordering goods"
  --data-urlencode "${LLM_MODELS_USED}[]=OpenAI GPT family"
  --data-urlencode "${LLM_MODELS_USED}[]=Anthropic Claude family"
  --data-urlencode "${EXACT_LLM_MODEL_NAMES}=Example model family/version if known"
  --data-urlencode "${OWNER_LOCATIONS}=Country/region/city or metro only; no exact street address"
  --data-urlencode "${OWNER_LOCATION_FLAGS}[]=One primary location"
  --data-urlencode "${TARGET_BUSINESS_LOCATIONS}=Country/region/city/service area; no private address"
  --data-urlencode "${TARGET_LOCATION_FLAGS}[]=Multiple local areas"
  --data-urlencode "${INDUSTRIES_CONTACTED}[]=Healthcare/HMOs/health plans"
  --data-urlencode "${INDUSTRIES_CONTACTED}[]=Grocery/retail"
  --data-urlencode "${INDUSTRIES_CONTACT_FREQUENCY}=1-2 per week"
  --data-urlencode "${TOP_BOTTLENECK_INDUSTRIES}[]=Healthcare/HMOs/health plans"
  --data-urlencode "${TOP_BOTTLENECK_INDUSTRIES}[]=Grocery/retail"
  --data-urlencode "${SERVICES_TRIED}[]=Appointments"
  --data-urlencode "${SERVICES_TRIED}[]=Customer support"
  --data-urlencode "${SERVICES_TRIED_FREQUENCY}=3-6 per week"
  --data-urlencode "${GOODS_TRIED}[]=Groceries"
  --data-urlencode "${GOODS_TRIED_FREQUENCY}=1-3 per month"
  --data-urlencode "${PURCHASING_DIFFICULTY_FACTORS}[]=Prices"
  --data-urlencode "${PURCHASING_DIFFICULTY_FACTORS}[]=Checkout"
  --data-urlencode "${TECHNICAL_ISSUES}[]=CAPTCHA/human verification"
  --data-urlencode "${TECHNICAL_ISSUES}[]=2FA that the agent cannot complete"
  --data-urlencode "${TECHNICAL_ISSUES}[]=No API/MCP/structured endpoint"
  --data-urlencode "${TOP_BOTTLENECK_REASONS}[]=No structured API/MCP/CLI"
  --data-urlencode "${TOP_BOTTLENECK_REASONS}[]=2FA barriers"
  --data-urlencode "${TOP_BOTTLENECK_REASONS}[]=Phone-only contact"
  --data-urlencode "${BOTTLENECK_FREQUENCY_OVERALL}=Often"
  --data-urlencode "${BOTTLENECK_FREQUENCY_MATRIX}=Example: CAPTCHA often; phone-only sometimes; no API often."
  --data-urlencode "${SIMPLEST_CONNECTION_METHODS}[]=MCP endpoint"
  --data-urlencode "${SIMPLEST_CONNECTION_METHODS}[]=Agent-readable API"
  --data-urlencode "${SIMPLEST_CONNECTION_METHODS}[]=HTTP POST/cURL (form-encoded)"
  --data-urlencode "${SIMPLEST_CONNECTION_METHODS}[]=Agent-friendly form submission"
  --data-urlencode "${SIMPLEST_CONNECTION_METHODS}[]=Machine-readable status/result updates"
  --data-urlencode "${BEST_CONTACT_CHANNELS}[]=Email"
  --data-urlencode "${BEST_CONTACT_CHANNELS}[]=Structured web form"
  --data-urlencode "${BEST_CONTACT_CHANNELS}[]=HTTP POST/cURL (form-encoded)"
  --data-urlencode "${WORST_CONTACT_CHANNELS}[]=Phone"
  --data-urlencode "${WORST_CONTACT_CHANNELS}[]=Email"
  --data-urlencode "${DISCOVERABILITY_SEARCH_SOURCES}[]=Google Search"
  --data-urlencode "${DISCOVERABILITY_SEARCH_SOURCES}[]=Moltbook community"
  --data-urlencode "${DISCOVERABILITY_SEARCH_SOURCES}[]=OpenClaw community"
  --data-urlencode "${DISCOVERABILITY_SEARCH_SOURCES}[other]="
  --data-urlencode "${SEARCH_FIRST_SOURCES}[]=Business website"
  --data-urlencode "${SEARCH_FIRST_SOURCES}[]=Search engine"
  --data-urlencode "${SEARCH_FALLBACK_SOURCES}[]=Phone/email"
  --data-urlencode "${PURCHASE_DECISION_INFLUENCED}=Often"
  --data-urlencode "${SELECTED_DIFFERENT_BUSINESS}=Yes sometimes"
  --data-urlencode "${PROVIDER_CHOICE_FACTORS}[]=Easier contact"
  --data-urlencode "${PROVIDER_CHOICE_FACTORS}[]=API support"
  --data-urlencode "${AGENT_POLICY_CLARITY}=Rarely"
  --data-urlencode "${USEFUL_PERMISSION_MODEL}[]=OAuth"
  --data-urlencode "${USEFUL_PERMISSION_MODEL}[]=Delegated auth"
  --data-urlencode "${USEFUL_PERMISSION_MODEL}[]=MCP auth"
  --data-urlencode "${EASIEST_VERIFICATION_METHODS}[]=OAuth"
  --data-urlencode "${EASIEST_VERIFICATION_METHODS}[]=Delegated auth"
  --data-urlencode "${EASIEST_VERIFICATION_METHODS}[]=Email confirmation"
  --data-urlencode "${EASIEST_VERIFICATION_METHODS}[]=SMS confirmation"
  --data-urlencode "${SECURITY_SAFETY_BLOCKERS}[]=CAPTCHA"
  --data-urlencode "${SECURITY_SAFETY_BLOCKERS}[]=2FA that the agent cannot complete"
  --data-urlencode "${SECURITY_SAFETY_BLOCKERS}[other]="
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Prompt injection in page content"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Credential leakage"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Concern about connecting payment-card access"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Concern about connecting bank-account access"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Concern about connecting email-account access"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Concern about connecting business account access"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Do not trust the company requesting access"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Do not understand why the requested access is needed"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Fear of unexpected charges"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[]=Prefer manual entry for sensitive data"
  --data-urlencode "${CAUTION_RISK_CONCERNS}[other]="
  --data-urlencode "${SENSITIVE_ACTION_APPROVAL_MODEL}[]=User confirmation before purchases"
  --data-urlencode "${SENSITIVE_ACTION_APPROVAL_MODEL}[]=Signed request"
  --data-urlencode "${SENSITIVE_ACTION_APPROVAL_MODEL}[]=Verified account"
  --data-urlencode "${SENSITIVE_ACTION_APPROVAL_MODEL}[]=Agent registry"
  --data-urlencode "${SENSITIVE_ACTION_APPROVAL_MODEL}[other]="
  --data-urlencode "${BUSINESS_SAFETY_MEASURES}[]=Delegated auth with scoped permissions"
  --data-urlencode "${BUSINESS_SAFETY_MEASURES}[]=Prompt-injection-resistant APIs"
  --data-urlencode "${BUSINESS_SAFETY_MEASURES}[]=Agent registry"
  --data-urlencode "${BUSINESS_SAFETY_MEASURES}[other]="
  --data-urlencode "${TASK_SUCCESS_PERCENTAGE}=41-60"
  --data-urlencode "${FAILURE_OUTCOMES}[]=Human handoff"
  --data-urlencode "${FAILURE_OUTCOMES}[]=Different provider"
  --data-urlencode "${SUCCESS_RATE_IMPROVEMENTS}[]=MCP support"
  --data-urlencode "${SUCCESS_RATE_IMPROVEMENTS}[]=APIs"
  --data-urlencode "${OVERALL_DIFFICULTY_RATING}=4"
  --data-urlencode "${OVERALL_BOTTLENECK_FREQUENCY_RATING}=4"
  --data-urlencode "${BOTTLENECK_SEVERITY_MATRIX}=Example: no structured endpoint 5; CAPTCHA 4; slow response 3."
  --data-urlencode "${PRIORITY_INDUSTRY_RANK_1}=Healthcare/HMOs/health plans"
  --data-urlencode "${PRIORITY_INDUSTRY_RANK_2}=Government/public services"
  --data-urlencode "${PRIORITY_INDUSTRY_RANK_3}=Grocery/retail"
  --data-urlencode "${IMPROVEMENT_POINT_ALLOCATION}=MCP/API/CLI 35; better discovery 15; booking/checkout 20; reliability 10; trust/verification 10; stronger model/more context 10."
  --data-urlencode "${AGENT_READY_RATING}=2"
  --data-urlencode "${GREATEST_BOTTLENECK_INDUSTRIES}[]=Healthcare/HMOs/health plans"
  --data-urlencode "${GREATEST_BOTTLENECK_INDUSTRIES}[]=Government/public services"
  --data-urlencode "${SERIOUS_BOTTLENECK_INDUSTRY_RANK_1}=Healthcare/HMOs/health plans"
  --data-urlencode "${SERIOUS_BOTTLENECK_INDUSTRY_RANK_2}=Government/public services"
  --data-urlencode "${SERIOUS_BOTTLENECK_INDUSTRY_RANK_3}=Grocery/retail"
  --data-urlencode "${TOP_RANKED_INDUSTRY_REASON}[]=No structured API/MCP/CLI"
  --data-urlencode "${TOP_RANKED_INDUSTRY_REASON}[]=CAPTCHA/human-only verification"
  --data-urlencode "${TOP_RANKED_INDUSTRY_REASON}[]=2FA barriers"
  --data-urlencode "${SINGLE_BIGGEST_IMPROVEMENT}=MCP server support"
  --data-urlencode "${SELF_REPORTED_SOURCE}=GitHub"
  --data-urlencode "${OPEN_COMMENT_ADDITIONAL_USE_CASES}=Optional sanitized note."
  --data-urlencode "${OPEN_COMMENT_FRUSTRATING_SITUATION}=Optional sanitized example with no private data."
  --data-urlencode "${OPEN_COMMENT_BUSINESS_CHANGES}=Optional recommendation."
  --data-urlencode "${OPEN_COMMENT_SURVEY_FEEDBACK}=Optional survey feedback."
  --data-urlencode "${FOLLOW_UP_CONSENT}=Yes"
  --data-urlencode "${OPTIONAL_FOLLOW_UP_CONTACT}=example@gmail.com"
)

curl "${curl_args[@]}"
